name: meypato
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.2.0
  supabase_flutter: ^2.10.0
  geolocator: ^14.0.2
  http: ^1.5.0
  image_picker: ^1.2.0
  image_picker_for_web: ^3.1.0
  intl: ^0.20.2
  path: ^1.9.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  provider: ^6.1.5+1
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/
